import Foundation

enum TwilightWarpExporter {
    private static let presetNames: [String: String] = [
        "#cba6f7": "Catppuccin Mocha",
        "#7aa2f7": "Tokyo Night",
        "#bd93f9": "Dracula",
        "#88c0d0": "Nord",
        "#fabd2f": "Gruvbox",
        "#ebbcba": "Rosé Pine",
    ]

    static func export(
        theme: TwilightTheme,
        seedHex: String,
        directory: URL = FileManager.default.urls(for: .downloadsDirectory, in: .userDomainMask).first ?? FileManager.default.homeDirectoryForCurrentUser,
        fileManager: FileManager = .default
    ) throws -> URL {
        let normalizedSeed = TwilightTheme.migratedSeedHex(seedHex)
        let name = presetNames[normalizedSeed] ?? "Custom \(normalizedSeed)"
        let slug = presetNames[normalizedSeed]
            .flatMap { $0.split(separator: " ").first.map(String.init) }?
            .lowercased()
            ?? "custom-\(normalizedSeed.dropFirst())"
        let fileURL = directory.appendingPathComponent("\(slug).yaml")

        try fileManager.createDirectory(at: directory, withIntermediateDirectories: true)
        try yaml(theme: theme, seedHex: normalizedSeed, name: name)
            .write(to: fileURL, atomically: true, encoding: .utf8)
        return fileURL
    }

    private static func yaml(theme: TwilightTheme, seedHex: String, name: String) -> String {
        let normal = theme.ghostty.normal
        let bright = theme.ghostty.bright
        return """
        # \(name) - generated by Argo from \(seedHex)
        # Install: copy to ~/.warp/themes/ and choose it in Warp Settings > Appearance > Themes.
        # Window transparency is configured outside this color theme.
        name: \(name)
        accent: '\(theme.ghostty.accent)'
        background: '\(theme.ghostty.background)'
        foreground: '\(theme.ghostty.foreground)'
        details: darker
        terminal_colors:
          normal:
            black:   '\(normal.black.hex)'
            red:     '\(normal.red.hex)'
            green:   '\(normal.green.hex)'
            yellow:  '\(normal.yellow.hex)'
            blue:    '\(normal.blue.hex)'
            magenta: '\(normal.magenta.hex)'
            cyan:    '\(normal.cyan.hex)'
            white:   '\(normal.white.hex)'
          bright:
            black:   '\(bright.black.hex)'
            red:     '\(bright.red.hex)'
            green:   '\(bright.green.hex)'
            yellow:  '\(bright.yellow.hex)'
            blue:    '\(bright.blue.hex)'
            magenta: '\(bright.magenta.hex)'
            cyan:    '\(bright.cyan.hex)'
            white:   '\(bright.white.hex)'
        """
        + "\n"
    }
}
